//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: claw_shark_curve
// ----------------------------------------------------------------------------
pub mod claw_shark_curve {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for claw_shark_curve
    pub fn program_id() -> Pubkey {
        pubkey!("CLAW2222222222222222222222222222222222222222")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: BuyTokens
    // ....................................................................

    /// Main instruction struct for BuyTokens
    pub struct BuyTokensInstruction {
        pub accounts: BuyTokensInstructionAccountMetas,
        pub data: BuyTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BuyTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct BuyTokensInstructionAccountMetas {
        pub launch: AccountMeta,

        pub purchase: AccountMeta,

        pub agent_record: AccountMeta,

        pub buyer: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for BuyTokens instruction
    #[derive(Debug, Clone)]
    pub struct BuyTokensInstructionAccounts {
        pub launch: Pubkey,

        pub purchase: Pubkey,

        pub agent_record: Pubkey,

        pub buyer: Pubkey,
    }

    impl BuyTokensInstructionAccounts {
        pub fn new(launch: Pubkey, purchase: Pubkey, agent_record: Pubkey, buyer: Pubkey) -> Self {
            Self {
                launch,

                purchase,

                agent_record,

                buyer,
            }
        }
    }

    /// Instruction data for BuyTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BuyTokensInstructionData {
        pub usdc_amount: u64,
    }

    impl BuyTokensInstructionData {
        pub fn new(usdc_amount: u64) -> Self {
            Self { usdc_amount }
        }
    }

    /// Implementation for BuyTokensInstruction
    impl BuyTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [189u8, 21u8, 230u8, 133u8, 247u8, 2u8, 110u8, 42u8]
        }

        pub fn data(data: BuyTokensInstructionData) -> Self {
            Self {
                accounts: BuyTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BuyTokensInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new(accounts.launch, false);

            self.accounts.purchase = AccountMeta::new(accounts.purchase, false);

            self.accounts.agent_record = AccountMeta::new_readonly(accounts.agent_record, false);

            self.accounts.buyer = AccountMeta::new(accounts.buyer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.push(self.accounts.purchase.clone());

            metas.push(self.accounts.agent_record.clone());

            metas.push(self.accounts.buyer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateLaunch
    // ....................................................................

    /// Main instruction struct for CreateLaunch
    pub struct CreateLaunchInstruction {
        pub accounts: CreateLaunchInstructionAccountMetas,
        pub data: CreateLaunchInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateLaunch instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateLaunchInstructionAccountMetas {
        pub launch: AccountMeta,

        pub founder: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateLaunch instruction
    #[derive(Debug, Clone)]
    pub struct CreateLaunchInstructionAccounts {
        pub launch: Pubkey,

        pub founder: Pubkey,
    }

    impl CreateLaunchInstructionAccounts {
        pub fn new(launch: Pubkey, founder: Pubkey) -> Self {
            Self { launch, founder }
        }
    }

    /// Instruction data for CreateLaunch
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateLaunchInstructionData {
        pub name: String,

        pub symbol: String,

        pub total_supply: u64,

        pub initial_price_lamports: u64,

        pub curve_slope: u64,

        pub migration_threshold: u64,
    }

    impl CreateLaunchInstructionData {
        pub fn new(
            name: String,

            symbol: String,

            total_supply: u64,

            initial_price_lamports: u64,

            curve_slope: u64,

            migration_threshold: u64,
        ) -> Self {
            Self {
                name,

                symbol,

                total_supply,

                initial_price_lamports,

                curve_slope,

                migration_threshold,
            }
        }
    }

    /// Implementation for CreateLaunchInstruction
    impl CreateLaunchInstruction {
        fn discriminator() -> [u8; 8] {
            [239u8, 223u8, 255u8, 134u8, 39u8, 121u8, 127u8, 62u8]
        }

        pub fn data(data: CreateLaunchInstructionData) -> Self {
            Self {
                accounts: CreateLaunchInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateLaunchInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new(accounts.launch, false);

            self.accounts.founder = AccountMeta::new(accounts.founder, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.push(self.accounts.founder.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateVault
    // ....................................................................

    /// Main instruction struct for CreateVault
    pub struct CreateVaultInstruction {
        pub accounts: CreateVaultInstructionAccountMetas,
        pub data: CreateVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateVaultInstructionAccountMetas {
        pub vault: AccountMeta,

        pub owner: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateVault instruction
    #[derive(Debug, Clone)]
    pub struct CreateVaultInstructionAccounts {
        pub vault: Pubkey,

        pub owner: Pubkey,
    }

    impl CreateVaultInstructionAccounts {
        pub fn new(vault: Pubkey, owner: Pubkey) -> Self {
            Self { vault, owner }
        }
    }

    /// Instruction data for CreateVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateVaultInstructionData {
        pub max_per_project: u64,

        pub daily_limit: u64,

        pub min_score: u8,

        pub require_consensus: bool,
    }

    impl CreateVaultInstructionData {
        pub fn new(
            max_per_project: u64,

            daily_limit: u64,

            min_score: u8,

            require_consensus: bool,
        ) -> Self {
            Self {
                max_per_project,

                daily_limit,

                min_score,

                require_consensus,
            }
        }
    }

    /// Implementation for CreateVaultInstruction
    impl CreateVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [29u8, 237u8, 247u8, 208u8, 193u8, 82u8, 54u8, 135u8]
        }

        pub fn data(data: CreateVaultInstructionData) -> Self {
            Self {
                accounts: CreateVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateVaultInstructionAccounts) -> Self {
            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DepositVault
    // ....................................................................

    /// Main instruction struct for DepositVault
    pub struct DepositVaultInstruction {
        pub accounts: DepositVaultInstructionAccountMetas,
        pub data: DepositVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DepositVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositVaultInstructionAccountMetas {
        pub vault: AccountMeta,

        pub owner: AccountMeta,
    }

    /// Account pubkeys for DepositVault instruction
    #[derive(Debug, Clone)]
    pub struct DepositVaultInstructionAccounts {
        pub vault: Pubkey,

        pub owner: Pubkey,
    }

    impl DepositVaultInstructionAccounts {
        pub fn new(vault: Pubkey, owner: Pubkey) -> Self {
            Self { vault, owner }
        }
    }

    /// Instruction data for DepositVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositVaultInstructionData {
        pub amount: u64,
    }

    impl DepositVaultInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for DepositVaultInstruction
    impl DepositVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [126u8, 224u8, 21u8, 255u8, 228u8, 53u8, 117u8, 33u8]
        }

        pub fn data(data: DepositVaultInstructionData) -> Self {
            Self {
                accounts: DepositVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositVaultInstructionAccounts) -> Self {
            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.owner.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: GetPrice
    // ....................................................................

    /// Main instruction struct for GetPrice
    pub struct GetPriceInstruction {
        pub accounts: GetPriceInstructionAccountMetas,
        pub data: GetPriceInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for GetPrice instruction
    #[derive(Debug, Clone, Default)]
    pub struct GetPriceInstructionAccountMetas {
        pub launch: AccountMeta,
    }

    /// Account pubkeys for GetPrice instruction
    #[derive(Debug, Clone)]
    pub struct GetPriceInstructionAccounts {
        pub launch: Pubkey,
    }

    impl GetPriceInstructionAccounts {
        pub fn new(launch: Pubkey) -> Self {
            Self { launch }
        }
    }

    /// Instruction data for GetPrice
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct GetPriceInstructionData {}

    impl GetPriceInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for GetPriceInstruction
    impl GetPriceInstruction {
        fn discriminator() -> [u8; 8] {
            [238u8, 38u8, 193u8, 106u8, 228u8, 32u8, 210u8, 33u8]
        }

        pub fn data(data: GetPriceInstructionData) -> Self {
            Self {
                accounts: GetPriceInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: GetPriceInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new_readonly(accounts.launch, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SellTokens
    // ....................................................................

    /// Main instruction struct for SellTokens
    pub struct SellTokensInstruction {
        pub accounts: SellTokensInstructionAccountMetas,
        pub data: SellTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SellTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct SellTokensInstructionAccountMetas {
        pub launch: AccountMeta,

        pub seller: AccountMeta,
    }

    /// Account pubkeys for SellTokens instruction
    #[derive(Debug, Clone)]
    pub struct SellTokensInstructionAccounts {
        pub launch: Pubkey,

        pub seller: Pubkey,
    }

    impl SellTokensInstructionAccounts {
        pub fn new(launch: Pubkey, seller: Pubkey) -> Self {
            Self { launch, seller }
        }
    }

    /// Instruction data for SellTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SellTokensInstructionData {
        pub token_amount: u64,
    }

    impl SellTokensInstructionData {
        pub fn new(token_amount: u64) -> Self {
            Self { token_amount }
        }
    }

    /// Implementation for SellTokensInstruction
    impl SellTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [114u8, 242u8, 25u8, 12u8, 62u8, 126u8, 92u8, 2u8]
        }

        pub fn data(data: SellTokensInstructionData) -> Self {
            Self {
                accounts: SellTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SellTokensInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new(accounts.launch, false);

            self.accounts.seller = AccountMeta::new(accounts.seller, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.push(self.accounts.seller.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawVault
    // ....................................................................

    /// Main instruction struct for WithdrawVault
    pub struct WithdrawVaultInstruction {
        pub accounts: WithdrawVaultInstructionAccountMetas,
        pub data: WithdrawVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawVaultInstructionAccountMetas {
        pub vault: AccountMeta,

        pub owner: AccountMeta,
    }

    /// Account pubkeys for WithdrawVault instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawVaultInstructionAccounts {
        pub vault: Pubkey,

        pub owner: Pubkey,
    }

    impl WithdrawVaultInstructionAccounts {
        pub fn new(vault: Pubkey, owner: Pubkey) -> Self {
            Self { vault, owner }
        }
    }

    /// Instruction data for WithdrawVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawVaultInstructionData {
        pub amount: u64,
    }

    impl WithdrawVaultInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawVaultInstruction
    impl WithdrawVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [135u8, 7u8, 237u8, 120u8, 149u8, 94u8, 95u8, 7u8]
        }

        pub fn data(data: WithdrawVaultInstructionData) -> Self {
            Self {
                accounts: WithdrawVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawVaultInstructionAccounts) -> Self {
            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.owner.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: claw_shark
// ----------------------------------------------------------------------------
pub mod claw_shark {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for claw_shark
    pub fn program_id() -> Pubkey {
        pubkey!("CLAW1111111111111111111111111111111111111111")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: ClaimRefund
    // ....................................................................

    /// Main instruction struct for ClaimRefund
    pub struct ClaimRefundInstruction {
        pub accounts: ClaimRefundInstructionAccountMetas,
        pub data: ClaimRefundInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimRefund instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimRefundInstructionAccountMetas {
        pub launch: AccountMeta,

        pub commitment: AccountMeta,

        pub funder: AccountMeta,

        pub vault_token_account: AccountMeta,

        pub funder_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ClaimRefund instruction
    #[derive(Debug, Clone)]
    pub struct ClaimRefundInstructionAccounts {
        pub launch: Pubkey,

        pub commitment: Pubkey,

        pub funder: Pubkey,

        pub vault_token_account: Pubkey,

        pub funder_token_account: Pubkey,
    }

    impl ClaimRefundInstructionAccounts {
        pub fn new(
            launch: Pubkey,

            commitment: Pubkey,

            funder: Pubkey,

            vault_token_account: Pubkey,

            funder_token_account: Pubkey,
        ) -> Self {
            Self {
                launch,

                commitment,

                funder,

                vault_token_account,

                funder_token_account,
            }
        }
    }

    /// Instruction data for ClaimRefund
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimRefundInstructionData {}

    impl ClaimRefundInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ClaimRefundInstruction
    impl ClaimRefundInstruction {
        fn discriminator() -> [u8; 8] {
            [15u8, 16u8, 30u8, 161u8, 255u8, 228u8, 97u8, 60u8]
        }

        pub fn data(data: ClaimRefundInstructionData) -> Self {
            Self {
                accounts: ClaimRefundInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimRefundInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new(accounts.launch, false);

            self.accounts.commitment = AccountMeta::new(accounts.commitment, false);

            self.accounts.funder = AccountMeta::new(accounts.funder, true);

            self.accounts.vault_token_account =
                AccountMeta::new(accounts.vault_token_account, false);

            self.accounts.funder_token_account =
                AccountMeta::new(accounts.funder_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.push(self.accounts.commitment.clone());

            metas.push(self.accounts.funder.clone());

            metas.push(self.accounts.vault_token_account.clone());

            metas.push(self.accounts.funder_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CommitFunds
    // ....................................................................

    /// Main instruction struct for CommitFunds
    pub struct CommitFundsInstruction {
        pub accounts: CommitFundsInstructionAccountMetas,
        pub data: CommitFundsInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CommitFunds instruction
    #[derive(Debug, Clone, Default)]
    pub struct CommitFundsInstructionAccountMetas {
        pub launch: AccountMeta,

        pub commitment: AccountMeta,

        pub funder: AccountMeta,

        pub vault_token_account: AccountMeta,

        pub funder_token_account: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CommitFunds instruction
    #[derive(Debug, Clone)]
    pub struct CommitFundsInstructionAccounts {
        pub launch: Pubkey,

        pub commitment: Pubkey,

        pub funder: Pubkey,

        pub vault_token_account: Pubkey,

        pub funder_token_account: Pubkey,
    }

    impl CommitFundsInstructionAccounts {
        pub fn new(
            launch: Pubkey,

            commitment: Pubkey,

            funder: Pubkey,

            vault_token_account: Pubkey,

            funder_token_account: Pubkey,
        ) -> Self {
            Self {
                launch,

                commitment,

                funder,

                vault_token_account,

                funder_token_account,
            }
        }
    }

    /// Instruction data for CommitFunds
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CommitFundsInstructionData {
        pub amount: u64,
    }

    impl CommitFundsInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for CommitFundsInstruction
    impl CommitFundsInstruction {
        fn discriminator() -> [u8; 8] {
            [242u8, 226u8, 172u8, 204u8, 143u8, 241u8, 207u8, 248u8]
        }

        pub fn data(data: CommitFundsInstructionData) -> Self {
            Self {
                accounts: CommitFundsInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CommitFundsInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new(accounts.launch, false);

            self.accounts.commitment = AccountMeta::new(accounts.commitment, false);

            self.accounts.funder = AccountMeta::new(accounts.funder, true);

            self.accounts.vault_token_account =
                AccountMeta::new(accounts.vault_token_account, false);

            self.accounts.funder_token_account =
                AccountMeta::new(accounts.funder_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.push(self.accounts.commitment.clone());

            metas.push(self.accounts.funder.clone());

            metas.push(self.accounts.vault_token_account.clone());

            metas.push(self.accounts.funder_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateLaunch
    // ....................................................................

    /// Main instruction struct for CreateLaunch
    pub struct CreateLaunchInstruction {
        pub accounts: CreateLaunchInstructionAccountMetas,
        pub data: CreateLaunchInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateLaunch instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateLaunchInstructionAccountMetas {
        pub launch: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateLaunch instruction
    #[derive(Debug, Clone)]
    pub struct CreateLaunchInstructionAccounts {
        pub launch: Pubkey,

        pub authority: Pubkey,
    }

    impl CreateLaunchInstructionAccounts {
        pub fn new(launch: Pubkey, authority: Pubkey) -> Self {
            Self { launch, authority }
        }
    }

    /// Instruction data for CreateLaunch
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateLaunchInstructionData {
        pub name: String,

        pub raise_goal: u64,

        pub raise_cap: Option<u64>,

        pub deadline: i64,

        pub quality_score: u8,
    }

    impl CreateLaunchInstructionData {
        pub fn new(
            name: String,

            raise_goal: u64,

            raise_cap: Option<u64>,

            deadline: i64,

            quality_score: u8,
        ) -> Self {
            Self {
                name,

                raise_goal,

                raise_cap,

                deadline,

                quality_score,
            }
        }
    }

    /// Implementation for CreateLaunchInstruction
    impl CreateLaunchInstruction {
        fn discriminator() -> [u8; 8] {
            [239u8, 223u8, 255u8, 134u8, 39u8, 121u8, 127u8, 62u8]
        }

        pub fn data(data: CreateLaunchInstructionData) -> Self {
            Self {
                accounts: CreateLaunchInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateLaunchInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new(accounts.launch, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FinalizeLaunch
    // ....................................................................

    /// Main instruction struct for FinalizeLaunch
    pub struct FinalizeLaunchInstruction {
        pub accounts: FinalizeLaunchInstructionAccountMetas,
        pub data: FinalizeLaunchInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FinalizeLaunch instruction
    #[derive(Debug, Clone, Default)]
    pub struct FinalizeLaunchInstructionAccountMetas {
        pub launch: AccountMeta,

        pub authority: AccountMeta,
    }

    /// Account pubkeys for FinalizeLaunch instruction
    #[derive(Debug, Clone)]
    pub struct FinalizeLaunchInstructionAccounts {
        pub launch: Pubkey,

        pub authority: Pubkey,
    }

    impl FinalizeLaunchInstructionAccounts {
        pub fn new(launch: Pubkey, authority: Pubkey) -> Self {
            Self { launch, authority }
        }
    }

    /// Instruction data for FinalizeLaunch
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FinalizeLaunchInstructionData {}

    impl FinalizeLaunchInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FinalizeLaunchInstruction
    impl FinalizeLaunchInstruction {
        fn discriminator() -> [u8; 8] {
            [113u8, 133u8, 62u8, 196u8, 58u8, 212u8, 118u8, 166u8]
        }

        pub fn data(data: FinalizeLaunchInstructionData) -> Self {
            Self {
                accounts: FinalizeLaunchInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FinalizeLaunchInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new(accounts.launch, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.push(self.accounts.authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RecordAgentScore
    // ....................................................................

    /// Main instruction struct for RecordAgentScore
    pub struct RecordAgentScoreInstruction {
        pub accounts: RecordAgentScoreInstructionAccountMetas,
        pub data: RecordAgentScoreInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RecordAgentScore instruction
    #[derive(Debug, Clone, Default)]
    pub struct RecordAgentScoreInstructionAccountMetas {
        pub launch: AccountMeta,

        pub agent_record: AccountMeta,

        pub oracle: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RecordAgentScore instruction
    #[derive(Debug, Clone)]
    pub struct RecordAgentScoreInstructionAccounts {
        pub launch: Pubkey,

        pub agent_record: Pubkey,

        pub oracle: Pubkey,
    }

    impl RecordAgentScoreInstructionAccounts {
        pub fn new(launch: Pubkey, agent_record: Pubkey, oracle: Pubkey) -> Self {
            Self {
                launch,

                agent_record,

                oracle,
            }
        }
    }

    /// Instruction data for RecordAgentScore
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RecordAgentScoreInstructionData {
        pub agent_id: String,

        pub score: u8,

        pub verdict: u8,
    }

    impl RecordAgentScoreInstructionData {
        pub fn new(agent_id: String, score: u8, verdict: u8) -> Self {
            Self {
                agent_id,

                score,

                verdict,
            }
        }
    }

    /// Implementation for RecordAgentScoreInstruction
    impl RecordAgentScoreInstruction {
        fn discriminator() -> [u8; 8] {
            [250u8, 174u8, 61u8, 80u8, 184u8, 105u8, 211u8, 25u8]
        }

        pub fn data(data: RecordAgentScoreInstructionData) -> Self {
            Self {
                accounts: RecordAgentScoreInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RecordAgentScoreInstructionAccounts) -> Self {
            self.accounts.launch = AccountMeta::new_readonly(accounts.launch, false);

            self.accounts.agent_record = AccountMeta::new(accounts.agent_record, false);

            self.accounts.oracle = AccountMeta::new(accounts.oracle, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.launch.clone());

            metas.push(self.accounts.agent_record.clone());

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AgentVault
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AgentVault {
    pub owner: Pubkey,

    pub balance: u64,

    pub max_per_project: u64,

    pub daily_limit: u64,

    pub daily_spent: u64,

    pub last_reset: i64,

    pub min_score: u8,

    pub require_consensus: bool,

    pub is_active: bool,

    pub total_invested: u64,

    pub total_returns: u64,

    pub bump: u8,
}

impl AgentVault {
    pub fn new(
        owner: Pubkey,

        balance: u64,

        max_per_project: u64,

        daily_limit: u64,

        daily_spent: u64,

        last_reset: i64,

        min_score: u8,

        require_consensus: bool,

        is_active: bool,

        total_invested: u64,

        total_returns: u64,

        bump: u8,
    ) -> Self {
        Self {
            owner,

            balance,

            max_per_project,

            daily_limit,

            daily_spent,

            last_reset,

            min_score,

            require_consensus,

            is_active,

            total_invested,

            total_returns,

            bump,
        }
    }
}

/// Custom struct: Launch
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Launch {
    pub authority: Pubkey,

    pub name: String,

    pub symbol: String,

    pub total_supply: u64,

    pub tokens_sold: u64,

    pub usdc_collected: u64,

    pub initial_price: u64,

    pub curve_slope: u64,

    pub migration_threshold: u64,

    pub migrated: bool,

    pub created_at: i64,

    pub agent_buys: u64,

    pub total_buyers: u64,

    pub bump: u8,
}

impl Launch {
    pub fn new(
        authority: Pubkey,

        name: String,

        symbol: String,

        total_supply: u64,

        tokens_sold: u64,

        usdc_collected: u64,

        initial_price: u64,

        curve_slope: u64,

        migration_threshold: u64,

        migrated: bool,

        created_at: i64,

        agent_buys: u64,

        total_buyers: u64,

        bump: u8,
    ) -> Self {
        Self {
            authority,

            name,

            symbol,

            total_supply,

            tokens_sold,

            usdc_collected,

            initial_price,

            curve_slope,

            migration_threshold,

            migrated,

            created_at,

            agent_buys,

            total_buyers,

            bump,
        }
    }
}

/// Custom struct: MigrationTriggered
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MigrationTriggered {
    pub launch: Pubkey,

    pub market_cap: u64,

    pub total_buyers: u64,

    pub agent_buys: u64,
}

impl MigrationTriggered {
    pub fn new(launch: Pubkey, market_cap: u64, total_buyers: u64, agent_buys: u64) -> Self {
        Self {
            launch,

            market_cap,

            total_buyers,

            agent_buys,
        }
    }
}

/// Custom struct: PriceQuery
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PriceQuery {
    pub launch: Pubkey,

    pub current_price: u64,

    pub tokens_sold: u64,

    pub market_cap: u64,
}

impl PriceQuery {
    pub fn new(launch: Pubkey, current_price: u64, tokens_sold: u64, market_cap: u64) -> Self {
        Self {
            launch,

            current_price,

            tokens_sold,

            market_cap,
        }
    }
}

/// Custom struct: Purchase
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Purchase {
    pub buyer: Pubkey,

    pub launch: Pubkey,

    pub usdc_paid: u64,

    pub tokens_received: u64,

    pub price_at_buy: u64,

    pub is_agent: bool,

    pub timestamp: i64,

    pub bump: u8,
}

impl Purchase {
    pub fn new(
        buyer: Pubkey,

        launch: Pubkey,

        usdc_paid: u64,

        tokens_received: u64,

        price_at_buy: u64,

        is_agent: bool,

        timestamp: i64,

        bump: u8,
    ) -> Self {
        Self {
            buyer,

            launch,

            usdc_paid,

            tokens_received,

            price_at_buy,

            is_agent,

            timestamp,

            bump,
        }
    }
}

/// Custom struct: TokensPurchased
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensPurchased {
    pub launch: Pubkey,

    pub buyer: Pubkey,

    pub usdc_paid: u64,

    pub tokens_received: u64,

    pub new_price: u64,

    pub is_agent: bool,
}

impl TokensPurchased {
    pub fn new(
        launch: Pubkey,

        buyer: Pubkey,

        usdc_paid: u64,

        tokens_received: u64,

        new_price: u64,

        is_agent: bool,
    ) -> Self {
        Self {
            launch,

            buyer,

            usdc_paid,

            tokens_received,

            new_price,

            is_agent,
        }
    }
}

/// Custom struct: TokensSold
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensSold {
    pub launch: Pubkey,

    pub seller: Pubkey,

    pub tokens_sold: u64,

    pub usdc_received: u64,

    pub fee: u64,
}

impl TokensSold {
    pub fn new(
        launch: Pubkey,

        seller: Pubkey,

        tokens_sold: u64,

        usdc_received: u64,

        fee: u64,
    ) -> Self {
        Self {
            launch,

            seller,

            tokens_sold,

            usdc_received,

            fee,
        }
    }
}

/// Custom struct: AgentRecord
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AgentRecord {
    pub launch: Pubkey,

    pub agent_id: String,

    pub score: u8,

    pub verdict: u8,

    pub timestamp: i64,

    pub bump: u8,
}

impl AgentRecord {
    pub fn new(
        launch: Pubkey,

        agent_id: String,

        score: u8,

        verdict: u8,

        timestamp: i64,

        bump: u8,
    ) -> Self {
        Self {
            launch,

            agent_id,

            score,

            verdict,

            timestamp,

            bump,
        }
    }
}

/// Custom struct: Commitment
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Commitment {
    pub launch: Pubkey,

    pub funder: Pubkey,

    pub amount: u64,

    pub timestamp: i64,

    pub bump: u8,
}

impl Commitment {
    pub fn new(launch: Pubkey, funder: Pubkey, amount: u64, timestamp: i64, bump: u8) -> Self {
        Self {
            launch,

            funder,

            amount,

            timestamp,

            bump,
        }
    }
}

/// Custom struct: FundsCommitted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct FundsCommitted {
    pub launch: Pubkey,

    pub funder: Pubkey,

    pub amount: u64,

    pub total_committed: u64,
}

impl FundsCommitted {
    pub fn new(launch: Pubkey, funder: Pubkey, amount: u64, total_committed: u64) -> Self {
        Self {
            launch,

            funder,

            amount,

            total_committed,
        }
    }
}

/// Custom struct: Launch
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Launch {
    pub authority: Pubkey,

    pub name: String,

    pub raise_goal: u64,

    pub raise_cap: Option<u64>,

    pub deadline: i64,

    pub quality_score: u8,

    pub total_committed: u64,

    pub funder_count: u32,

    pub status: LaunchStatus,

    pub created_at: i64,

    pub bump: u8,
}

impl Launch {
    pub fn new(
        authority: Pubkey,

        name: String,

        raise_goal: u64,

        raise_cap: Option<u64>,

        deadline: i64,

        quality_score: u8,

        total_committed: u64,

        funder_count: u32,

        status: LaunchStatus,

        created_at: i64,

        bump: u8,
    ) -> Self {
        Self {
            authority,

            name,

            raise_goal,

            raise_cap,

            deadline,

            quality_score,

            total_committed,

            funder_count,

            status,

            created_at,

            bump,
        }
    }
}

/// Custom struct: LaunchCreated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct LaunchCreated {
    pub launch: Pubkey,

    pub authority: Pubkey,

    pub name: String,

    pub raise_goal: u64,

    pub quality_score: u8,
}

impl LaunchCreated {
    pub fn new(
        launch: Pubkey,

        authority: Pubkey,

        name: String,

        raise_goal: u64,

        quality_score: u8,
    ) -> Self {
        Self {
            launch,

            authority,

            name,

            raise_goal,

            quality_score,
        }
    }
}

/// Custom struct: LaunchFunded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct LaunchFunded {
    pub launch: Pubkey,

    pub total_raised: u64,

    pub funder_count: u32,
}

impl LaunchFunded {
    pub fn new(launch: Pubkey, total_raised: u64, funder_count: u32) -> Self {
        Self {
            launch,

            total_raised,

            funder_count,
        }
    }
}

/// Custom struct: LaunchRefunding
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct LaunchRefunding {
    pub launch: Pubkey,

    pub total_committed: u64,

    pub goal: u64,
}

impl LaunchRefunding {
    pub fn new(launch: Pubkey, total_committed: u64, goal: u64) -> Self {
        Self {
            launch,

            total_committed,

            goal,
        }
    }
}

/// Custom enum: LaunchStatus
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum LaunchStatus {
    Live,

    Funded,

    Refunding,

    Completed,

    Failed,
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
